<a href="https://colab.research.google.com/github/WereszczynskiClasses/Phys240_Solutions/blob/main/Activity_Linear_Algebra_2_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Other matrix operations

Most matrix operations work as you'd expect in python.  For example, additions adds each of the elements of two matrices together and subtraction subtracts them.  There are a couple of important difference though which we'll note here, and some additional operations you should be aware of.

## Matrix multiplication

Be careful with matrix multiplication in python.  By default, if you use the ```*``` operation on two matrices you'll multiply each element of two arrays together, which is not what you want.  The solution is simple: use the ```@``` operator to multiply two matrices

**Activity** Define two matrices.  Matrix **A** should be a $3x4$ matrix and matrix **B** should be a $4x3$.  Try multiplying them together using the ```*``` operator and note the error that you get (it’s important to see these errors so that you know what they mean when you encounter them in coding).  Then try multiplying them using the ```@``` operator.

In [1]:
import numpy as np
B=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("A=\n",A)
print("B=\n",B)
A*B

A=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
B=
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


ValueError: ignored

In [2]:
print(A@B)

[[ 70  80  90]
 [158 184 210]
 [246 288 330]]


## Determinant calculations

The determinant of a matrix is a useful quantity for telling us if a square matrix is singular and invertible, and can be used to determine how well "conditioned" a matrix is (that is, how sensitive is the matrix in calculations such as in solving linear equations to small changes in the values).  To calculate it is straightforward.  In the scipy linalg package you can use the ```linalg.det``` function, such as:

```
from scipy import linalg

linalg.det(A)
```

**Activity** Calculate the determinant of the matrix:

$ 
\mathbf{A} =
\begin{pmatrix}
2 & 4 & 6 & 9\\
4 & 8& 3 & 4 \\
6 & 3 & 2 & 1 \\
9 & 4 & 1 & 1  \\
\end{pmatrix}
$

In [ ]:
from scipy import linalg
A= np.array([[2,4,6,9],[4,8,3,4],[6,3,2,1],[9,4,1,1]])
print("A=\n",A)
print("Determinant=",linalg.det(A))

A=
 [[2 4 6 9]
 [4 8 3 4]
 [6 3 2 1]
 [9 4 1 1]]
Determinant= -433.0


## Matrix transpose

The matrix transpose is simply flipping a matrix so that the rows become columns and the columns become rows.  This is easy to do in python.  If you have a matrix ```A```, you can compute the transpose of the matrix by either using the function:

```np.transpose(A)```

or the easier ways is to type:

```A.T```

Where the ```.T``` is for transpose.

**Activity** Compute the transpose of the matrix:

$\begin{pmatrix}
1 & 2 &3\\
4 & 5 &6
\end{pmatrix}
$

In [ ]:
A=np.array([[1,2,3],[4,5,6]])
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


## Identity Matrix

The identity matrix is the matrix equivalent of the number 1.  It has ones on the diagonal and zeros everywhere else.  For example:

$
\begin{pmatrix} 
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0 \\
0 & 0 & 1& 0 \\
0 & 0 & 0& 1
\end{pmatrix} 
$

is the $4x4$ identity matrix.  This can be computed in python with the command:

```np.eye(N)```

where $N$ is the same of the desired identity matrix.


 # QR Decomposition and Eigenvalues

Last class we saw how we can decompose (or factor) a matrix into two other matrices using the "LU decomposition," and how we can use those results to find solve systems of linear equations.  There are several other decomposition methods available, each of which have various uses.

Another common decomposition algorithm is "QR decomposition".  In this method, a square matrix $\mathbf{A}$ is factored into two matrices $\mathbf{Q}$ and $\mathbf{R}$:

$\mathbf{A}=\mathbf{QR}$

where $\mathbf{Q}$  is an orthogonal matrix (that is, each column is a vector that is orthogonal to each of the other columns) and $\mathbf{R}$ is an upper diagonal matrix (it's also called a right triangle matrix, hence why it is called $\mathbf{R}$).  We won't go into the algorithms that have been developed to calculate this decomposition, but for those that are interested I would recommend looking into the Gram–Schmidt, Househoulder, or Givens processes.

Of course, python has ways to compute the QR decomposition.  In SciPy, this is in the linalg module.  The function:

```
from scipy import linalg
Q, R = linalg.qr(A)
```

Will return the matrices **Q** and **R** for the matrix **A**.  Note that because **Q** is an orthogonal matrix it has the nice property that:

$
\mathbf{Q^T Q} = \mathbf{I}$

Where $\mathbf{I}$ is the identity matrix (this is because the *ij*th element of the matrix $\mathbf{Q^T Q}$ is the dot product of the $i$th and $j$th columns of $\mathbf{I}$, so it will be 1 if i=j and 0 otherwise.

**Activity**. Consider the matrix:

$ 
\mathbf{A} =
\begin{pmatrix}
2 & 4 & 6 & 9\\
4 & 8& 3 & 4 \\
6 & 3 & 2 & 1 \\
9 & 4 & 1 & 1  \\
\end{pmatrix}
$

Calculate the QR decomposition.  Use the results to show:

1.  That the product of **Q** and **R** equals **A**.

2.  That the product of $\mathbf{Q}$ and $\mathbf{Q^T}$ equals $I$.

3.  That each of the columns of Q is orthogonal from each other column.  Note that you might find the numpy dot product function useful for this:
 
  ```x = np.dot(a,b)```

   which calculates the dot product of vectors $a$ and $b$ and stores it as $x$.
   

In [ ]:
from scipy import linalg

A= np.array([[2,4,6,9],[4,8,3,4],[6,3,2,1],[9,4,1,1]])

Q,R=linalg.qr(A)
print("A=\n",A)
print("Q=\n",Q)
print("R=\n",R)

A=
 [[2 4 6 9]
 [4 8 3 4]
 [6 3 2 1]
 [9 4 1 1]]
Q=
 [[-0.17087153 -0.41289047  0.86769263  0.2177932 ]
 [-0.34174306 -0.82578093 -0.44392663 -0.0650129 ]
 [-0.51261459  0.17547845  0.18816589 -0.81916249]
 [-0.76892189  0.34178155 -0.12096379  0.52660446]]
R=
 [[-11.70469991  -8.03096198  -3.84460946  -4.18635252]
 [  0.          -6.36424777  -4.26194714  -6.50187792]
 [  0.           0.           4.1297439    6.10072927]
 [  0.           0.           0.           1.4075292 ]]


Note that $\mathbf{QR}=\mathbf{A}$

In [ ]:
print(Q@R)

[[2. 4. 6. 9.]
 [4. 8. 3. 4.]
 [6. 3. 2. 1.]
 [9. 4. 1. 1.]]


Note that $\mathbf{Q^T Q}=\mathbf{I}$

In [ ]:
print(Q.T@Q)

[[ 1.00000000e+00  8.01794500e-17 -7.22161982e-17 -9.50519865e-17]
 [ 8.01794500e-17  1.00000000e+00  9.08893577e-18  6.78343248e-18]
 [-7.22161982e-17  9.08893577e-18  1.00000000e+00  1.12207981e-16]
 [-9.50519865e-17  6.78343248e-18  1.12207981e-16  1.00000000e+00]]


We can get the same result by computing all of the different pairs of dot products between the columns of $\mathbf{Q}$.

In [ ]:
for i in range(4):
  for j in range(i,4):
    print("The dot product for column",i,"and",j,"is:",np.dot(Q[:,i],Q[:,j]))

The dot product for column 0 and 0 is: 1.0000000000000002
The dot product for column 0 and 1 is: 8.017945000873181e-17
The dot product for column 0 and 2 is: -7.221619823054915e-17
The dot product for column 0 and 3 is: -9.505198653113816e-17
The dot product for column 1 and 1 is: 1.0000000000000002
The dot product for column 1 and 2 is: 9.088935768406905e-18
The dot product for column 1 and 3 is: 6.783432480966266e-18
The dot product for column 2 and 2 is: 1.0
The dot product for column 2 and 3 is: 1.1220798092731282e-16
The dot product for column 3 and 3 is: 1.0


One of the most useful applications of QR decomposition is for calculating eigenvectors and eigenvalues.  As a reminder, for a symmetric matrix $\mathbf{A}$ an eigenvector $v$ is a vector which satisfies:

$\mathbf{Av} = \lambda\mathbf{v}$

 with $\lambda$ the corresponding eigenvalue.  We can calculate all of the eigenvectors and eigenvalues using the matrix equation:

 $\mathbf{AV} = \mathbf{VD}$

 Where  $\mathbf{V}$ is a matrix with each column corresponding to an eigenvector, and  $\mathbf{D}$ is a diagonal matrix with each of the diagonal elements corresponding to an eigenvalue.  That is, if $A$ is a $4x4$matrix,  $\mathbf{D}$ will look like:

 $
 \begin{pmatrix}
 \lambda_1 & 0 &0 &0 \\
 0 &\lambda_2 & 0 &0 \\
 0& 0 &\lambda_3 & 0  \\
 0& 0 &0& \lambda_4   
 \end{pmatrix}
 $

 To find $\mathbf{V}$, we take the following steps:
 
 1. We perform a QR factorization of $\mathbf{A}$:

  $\mathbf{A}=\mathbf{Q_1 R_1}$

 we then use the fact that $\mathbf{Q_1}$ is orthonormal (that is, $\mathbf{Q_1^T Q_1}=\mathbf{I}$) to get:

 $\mathbf{Q_1^T A}=\mathbf{Q_1^T Q_1 R_1}=\mathbf{R_1}$

 2.  We use the to define a new matrix $\mathbf{A_1}$ which is:

   $\mathbf{A_1}=\mathbf{R_1 Q_1}$

   which, using the above, we can rewrite as:

   $\mathbf{A_1}=\mathbf{Q_1^T R_1 Q_1}$

3.  We iterate this many times.  After $k$ steps we get a sequence of matrices:

   $\mathbf{A_1}=\mathbf{Q_1^T AQ_1}\\
   \mathbf{A_2}=\mathbf{Q_2^T Q_1^T AQ_1 Q_2}\\
   \mathbf{A_3}=\mathbf{Q_3^T Q_2^T Q_1^T A Q_1 Q_2 Q_3}\\
   \vdots \\
   \mathbf{A_k}=\mathbf{\left(Q_k^T ... Q_1^T\right) A \left(Q_1...Q_k\right)}
   $

4.  It can be shown (and you can certainly test) that as you repeat this process the matrix $\mathbf{A_k}$ becomes diagonal.  That is, we'll find that is $k$ becomes large we can approximate $\mathbf{D} \approx \mathbf{A_k}$.  We can define another matrix $\mathbf{V}$ as:

  $\mathbf{V} = \mathbf{\left(Q_1...Q_k\right)} = \prod_{i=1}^k \mathbf{Q_i}$.

  Note that since $\mathbf{V}$ is a product of orthogonal matrices, it is also orthogonal so we can use $\mathbf{V^T V} = \mathbf{V V^T} = \mathbf{I}$.  Putting this in our equation for $\mathbf{A_k}$ we get:

  $ \mathbf{D}=\mathbf{V^T A V}$

  Which we can multiply both sides by $\mathbf{V}$ to get:

  $ \mathbf{VD}=\mathbf{A V}$
  
  our definition for eigenvectors and eigenvalues!

 **Activity** Lets try implementing this algorithm.  To do this, write code that does the following:

1.  Create an $NxN$ matrix for $\mathbf{V}$ for the eigenvectors, and initially set it equal to the identity matrix $\mathbf{I} of the same size.

2. Calculate the QR decomposition of $\mathbf{A}=\mathbf{QR}$

3.  Update $\mathbf{A}$ to the new value $\mathbf{A}=\mathbf{RQ}$

4.  Update $\mathbf{V}$ to the new value $\mathbf{V}=\mathbf{VQ}$ (that is, multiply $\mathbf{V}$ on the right by $\mathbf{Q}$)

5.  Repeat steps 2-4 multiple times.  You should stop when the off-diagonal elements are below some small threshold.  Here, you can do this for a fixed number of iterations, or if you have time you can check the off-diagonal elements to see if they are below some small number (such as $10^{-8}$) and perform the above iterations until this criteria is met.

Try your code on the matrix $\mathbf{A}$ that we defined above.  When you are done, check to make sure your eigenvectors are all orthogonal to one another.

In [ ]:
import numpy as np
from scipy import linalg

This function is useful for determining the maximum off-diagonal element (there are more efficient ways this could be written, but this is fairly easy to understand).

In [ ]:
def max_offdiag(A):
  maxval = 0.0
  N=A.shape[0]
  for i in range(N):
    for j in range(N):
      if i != j and np.abs(A[i,j]) > maxval :
        maxval = np.abs(A[i,j])
  return maxval


First define our matrix.  Then perform iterations of our QR algorithm until the maximum off-diagonal element is below our threshold.  Then print the eigenvectors and eigenvalues.  Note that $\mathbf{V}$ is an orthonormal matrix.

In [ ]:
A= np.array([[2,4,6,9],[4,8,3,4],[6,3,2,1],[9,4,1,1]])

epsilon = 1e-8

V = np.identity(4)

maxerror = 1.0

while maxerror > epsilon:
  Q,R=linalg.qr(A)
  A = R@Q
  V = V@Q
  maxerror = max_offdiag(A)

print("Eigenvectors:\n",V)
print("Eigenvalues:\n")
for i in range(4):
  print(A[i,i])

for i in range(4):
  for j in range(i,4):
    print("The dot product for column",i,"and",j,"is: %6.4f"%np.dot(V[:,i],V[:,j]))

Eigenvectors:
 [[-0.56868399 -0.69840234  0.42736047  0.07871291]
 [-0.56477136 -0.04425133 -0.82405938  0.00112746]
 [-0.36423525  0.34329287  0.23005319 -0.83460064]
 [-0.47430425  0.62643914  0.29217237  0.5452016 ]]
Eigenvalues:

17.32175232021623
-8.768440625318817
3.669861887660925
0.7768264174416376
The dot product for column 0 and 0 is: 1.0000
The dot product for column 0 and 1 is: 0.0000
The dot product for column 0 and 2 is: 0.0000
The dot product for column 0 and 3 is: -0.0000
The dot product for column 1 and 1 is: 1.0000
The dot product for column 1 and 2 is: -0.0000
The dot product for column 1 and 3 is: -0.0000
The dot product for column 2 and 2 is: 1.0000
The dot product for column 2 and 3 is: 0.0000
The dot product for column 3 and 3 is: 1.0000


## Computing eigenvalues and eigenvectors with python

Similar to dealing with simultaneous linear equations, the problem of solving for eigenvalues and eigenvectors is so ubiquitous that they are built into standard python packages.  In particular, in numpy and scipy we can use the linear algebra's ```linalg.eig``` function:

```
evalues, evectors = linalg.eig(A)
```

will compute the eigenvalues (```lambda```) and matrix of eigenvectors (```V```) for the matrix ```A```.

**Activity** Try the linalg.eig function for the matrix you computed in the previous activity.  How do the results compare? (Be careful here, you may need to re-initialize your matrix $A$).

In [ ]:
A= np.array([[2,4,6,9],[4,8,3,4],[6,3,2,1],[9,4,1,1]])
evalues, evectors = linalg.eig(A)
print("Eigenvalues = \n",evalues)
print("Eigenvectors = \n",evectors)

Eigenvalues = 
 [17.32175232+0.j -8.76844063+0.j  3.66986189+0.j  0.77682642+0.j]
Eigenvectors = 
 [[ 0.56868399  0.69840234 -0.42736047  0.07871291]
 [ 0.56477136  0.04425133  0.82405938  0.00112746]
 [ 0.36423525 -0.34329287 -0.23005319 -0.83460064]
 [ 0.47430425 -0.62643914 -0.29217237  0.5452016 ]]


**Activity** With large datasets we often want to calculate eigenvectors and eigenvalues.  This can be particularly important for helping us to understand the how are system is changing when we have a lot of noisy data.  Similar to last class, use the ```timeit``` function to determine how big of a matrix you can realistically find the eigenvectors and eigenvalues of.  How does this compare to the maximum practical matrix size you found last class for solving simultaneous linear equations?

In [ ]:
%%timeit -n 10
N = 500
A=np.random.random([N,N])
linalg.eig(A)

10 loops, best of 5: 446 ms per loop


## Hermitian matrices (if you have time)

Oftentimes in physics we'll have matrices that are either symmetric with real numbers or Hermitian (that is, the real parts are symmetric and the complex parts are conjugates of one another for elements $a_{ij}$ and $a_{ji}$).  In fact, the QR algorithm above is only applicable for symmetric matrices.  The general ```linalg.eig``` function uses general routines for calculating eigenvectors and eigenvalues.  But if you have a symmetric matrix you can use more specific (and faster) algorithms.  In particular, the ```linalg.eigh``` function assumes you have a Hermitian matrix.  Repeat the above activity, trying the code below instead.  How much more efficient is this algorithm?  Note there is an additional line of ```A= A+ A.T``` which forces the matrix ```A``` to be symmetric.

In [ ]:
%%timeit -n 10
N = 500
A=np.random.random([N,N])
A = A+A.T
linalg.eigh(A)

10 loops, best of 5: 71.3 ms per loop
