<a href="https://colab.research.google.com/github/WereszczynskiClasses/Phys240_Solutions/blob/main/Activity_Linear_Equations_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Simultaneous Linear Equations

In many applications you'll be presented with a set of linear equations with multiple variables you have to solve.  For example, in Physics II you dealt with Kirchhoff’s rules, which gave you a set of voltage and current equations, and as long as your circuit only had resistors and batteries in it then all of the equations were linear.  

A simple set of simultaneous linear equations might look like this:

$2 x + y = 5$

$ x - 2y = 0$

In this case it’s pretty easy to find the solution by hand, and you've surely developed methods to find the solution.  However, these methods quickly become tedious and error-prone, and you wouldn't want to do this for more than a few variables.  But this is a perfect task for a computer: it's not going to get bored by doing a tedious task, and if the algorithm is well written it's not going to make a simple arithmetic error. 

The simplest way to approach this is to rewrite our simultaneous equations in matrix form. To do that, the above equations would become:

$
\begin{pmatrix}
 2 & 1 \\
 1 & -2
\end{pmatrix}
\begin{pmatrix}
 x \\ y
\end{pmatrix}
=
 \begin{pmatrix}
 5 \\ 0
\end{pmatrix}
$

Or, written in shorthand:

$\mathbf{Ax}=\mathbf{b}$. 

Where $\mathbf{x} = (x,y)$ and the matrix $\mathbf{A}$ and vector $\mathbf{b}$ take the values from our simultaneous linear equations.

**Activity:** Consider the set of linear equations:

$5 x + 4 y + z = 23$

$x - 2 y  = -6$

$3y + z = 9$

Write the matricies $\mathbf{A}$ and $\mathbf{b}$ that represent this set of linear equations  in the matrix formula $\mathbf{Ax}=\mathbf{b}$.


In [1]:
import numpy as np
A=np.array([[5,4,1],[1,-2,0],[0,3,4]])
b=np.array([23,-6,9])
print(A)
print(b)

[[ 5  4  1]
 [ 1 -2  0]
 [ 0  3  4]]
[23 -6  9]


## Gaussian Elimination

Gaussian elimination is a straightforward method to solve simultaneous linear equations.  It relies on two things:

1.  You can multiply both sides of any of the simultaneous equations by a constant and get the same answer.  Said another way: if we multiple any row of the matrix **A** by a constant, and we multiply the corresponding row of the vector **b** by the same constant, then the solution does not change.

2.  You can take any linear combination of two equations to get a new equation with the correct solution. Said another way: If we add to or subtract from any row of **A** a multiple of any other row, and we do the same for the vector **b**, then the solution does not change.

By alternating these steps, we can transform our original **A** and **b** into a new matrix and vector that are easier to solve for our unknown vector **x**.  

As an example, consider the following matrix equation:

$
\begin{pmatrix}
2 & 1& 4& 1\\
3 & 4& -1 & -1\\
1& -4& 1& 5\\
2& -2& 1& 3
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
-4\\3\\9\\7
\end{pmatrix}
$

To find the **x** vector, we first divide the top row of **A** and the top value of **b** by the top-left element of the matrix (which is 2 here) to get:

$
\begin{pmatrix}
1 & 0.5& 2& 0.5\\
3 & 4& -1 & -1\\
1& -4& 1& 5\\
2& -2& 1& 3
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
-2\\3\\9\\7
\end{pmatrix}
$

we then want the first element in the second row to be a zero.  To get that, we subtract from the second row of $A$ and $b$ three times the first row of $A$ and $b$ to get:

$
\begin{pmatrix}
1 & 0.5& 2& 0.5\\
0 & 2.5& -7 & -2.5\\
1& -4& 1& 5\\
2& 9& 1& 3
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
-2\\9\\9\\7
\end{pmatrix}
$

We can perform similar calculations on the third and fourth rows to get:

$
\begin{pmatrix}
1 & 0.5& 2& 0.5\\
0 & 2.5& -7 & -2.5\\
0& -4.5& -1& 4.5\\
0& -3& -3& 2
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
-2\\9\\11\\11
\end{pmatrix}
$

Next, we move on to the second row, repeating these same steps.  First, we divide the second row by the value of the second value to get:

$
\begin{pmatrix}
1 & 0.5& 2& 0.5\\
0 & 1& -2.8 & -1\\
0& -4.5& -1& 4.5\\
0& -3& -3& 2
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
-2\\3.6\\11\\11
\end{pmatrix}
$

And then we subtract from the third and fourth rows the appropriate values of the second row to leave:

$
\begin{pmatrix}
1 & 0.5& 2& 0.5\\
0 & 1& -2.8 & -1\\
0& -4.5& -1& 4.5\\
0& -3& -3& 2
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
-2\\3.6\\11\\11
\end{pmatrix}
$

Repeating this procedure on the third and fourth rows will give:

$
\begin{pmatrix}
1 & 0.5& 2& 0.5\\
0 & 1& -2.8 & -1\\
0& 0& 1& 0\\
0& 0& 0& 1
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
-2\\3.6\\-2\\1
\end{pmatrix}
$

After all of this work, we have a different set of simultaneous linear equations **that have the same solution as our first set of equations.** In general, we'll have a new set of equations that looks like this:

$
\begin{pmatrix}
1 & a_{01} &a_{02}& a_{03}\\
0 & 1& a_{12}& a_{13}\\
0& 0& 1& a_{23}\\
0& 0& 0& 1
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
b_1\\b_2\\b_3\\b_4
\end{pmatrix}
$

This set of equations is much easier to solve.  Performing the appropriate matrix multiplication, we get:

$w + a_{01} x + a_{02} y + a_{03} z = b_1$

$x + a_{12} y + a_{13} z = b_2 $

$y + a_{23} z = b_3 $

$ z = b_4$

Now you can almost just read off the solution! Or at the worst, find it with very little work.

## LU Decomposition

They key to Gaussian elimination is that we create an easier set of linear equations to solve.  It's easier because we transform our original matrix into one that has all zeros below the diagonal, so working backwards to find our solution is easy.  This matrix is termed an **upper diagonal** matrix since it only has positive values on or above the diagonal.  

The problem with Gaussian elimination is that if you change **b**, you have to repeat the whole calculation.  But note that all of our steps are dictated only by the values in our matrix **A**.  This implies that if we keep track of our steps in Gaussian elimination, we won't need to repeat them each time we want to solve for a new **b**.

We won't go through the derivation here, but the idea is that we can factor our matrix **A** into two other matrices, which we'll call **L** and **U** (yes, you can factor matrices just like you can factor numbers).  **U** is just the matrix we found above, and **L** is a matrix that keeps track of the steps we took to make **U** (for a more detailed description, see: [Wikipedia](https://en.wikipedia.org/wiki/LU_decomposition#Algorithms)).  That is, we can factor **A** into:

$\mathbf{A}=\mathbf{LU}$

As you might guess, **L** is a lower-diagonal matrix (that is, all values above the diagonal are zero).  We can substitute this into our original matrix equation to get:

$\mathbf{Ax}=\mathbf{LUx}=\mathbf{b}$

and noting that $\mathbf{Ux}$ is just another vector, which we'll call $\mathbf{y}$, we get:

$\mathbf{Ly}=\mathbf{b}$

and 

$\mathbf{Ux}=\mathbf{y}$

Both of these are fairly simple to solve, because in each case we are dealing with a diagonal matrix.

## Pivoting

While looking at the above procedure for Gaussian elimination, you may notice we could run into trouble if the leading term of a row is zero.  For example, if our original matrix equation looked like this:

$
\begin{pmatrix}
0 & 1& 4& 1\\
3 & 4& -1 & -1\\
1& -4& 1& 5\\
2& -2& 1& 3
\end{pmatrix}
\begin{pmatrix}
w \\x\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
-4\\3\\9\\7
\end{pmatrix}
$

Our algorithm would fail because we can't divide by zero.  The solution is easy: we just reorder the rows since it doesn't matter in what order we consider our linear equations.  To do that, we want to convert the above into this:

$
\begin{pmatrix}
3 & 4& -1 & -1\\
0 & 1& 4& 1\\
1& -4& 1& 5\\
2& -2& 1& 3
\end{pmatrix}
\begin{pmatrix}
x \\w\\y\\z
\end{pmatrix}
= 
\begin{pmatrix}
3\\-4\\9\\7
\end{pmatrix}
$

To do this in matrix calculations, we multiply our original matrix by a "pivot matrix," which we denote as **P**.  Here we get:

$
\mathbf{P}=\begin{pmatrix}
0&1&0&0 \\
1&0&0&0 \\
0&0&1&0 \\
0&0&0&1 
\end{pmatrix} 
$

Which has the feature of: 

$
\begin{pmatrix}
0&1&0&0 \\
1&0&0&0 \\
0&0&1&0 \\
0&0&0&1 
\end{pmatrix} 
\begin{pmatrix}
0 & 1& 4& 1\\
3 & 4& -1 & -1\\
1& -4& 1& 5\\
2& -2& 1& 3
\end{pmatrix} 
=
\begin{pmatrix}
3 & 4& -1 & -1\\
0 & 1& 4& 1\\
1& -4& 1& 5\\
2& -2& 1& 3
\end{pmatrix} 
$

In terms of LU decomposition, LU decomposition with pivoting results in the substitution of **A** with the three matrices **P**, **L**, and **U**:

$\mathbf{A}=\mathbf{PLU}$

## Python implementation

The algorithms for Gaussian elimination and LU decomposition looks complicated, but they only require a couple of steps.  While they wouldn't take that many steps, given the ubiquity of linear equations it shouldn't come as a surprise that python has built-in methods to perform these calculations. 

Although the numpy package we've using has a linear algebra section, the one in SciPy (Scientific Python) has a few more features.  To import it, issue the following command:

In [2]:
from scipy import linalg
import numpy as np

We'll want to use the ```lu``` function in the linalg library of scipy.  You can view the help for it here:

In [3]:
help(linalg.lu)

Help on function lu in module scipy.linalg.decomp_lu:

lu(a, permute_l=False, overwrite_a=False, check_finite=True)
    Compute pivoted LU decomposition of a matrix.
    
    The decomposition is::
    
        A = P L U
    
    where P is a permutation matrix, L lower triangular with unit
    diagonal elements, and U upper triangular.
    
    Parameters
    ----------
    a : (M, N) array_like
        Array to decompose
    permute_l : bool, optional
        Perform the multiplication P*L  (Default: do not permute)
    overwrite_a : bool, optional
        Whether to overwrite data in a (may improve performance)
    check_finite : bool, optional
        Whether to check that the input matrix contains only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if the inputs do contain infinities or NaNs.
    
    Returns
    -------
    **(If permute_l == False)**
    
    p : (M, M) ndarray
        Permutation matr

Note that this function requires one input (the matrix **A** from above) and returns three matricies, the **P**, **L**, and **U** matricies.  Try it on the simple 3x3 matrix below:

In [4]:
A = np.array([[1,8,2],[5,1,3],[2,4,7]])
P,L,U = linalg.lu(A)
print("A=\n",A)
print("P=\n",P)
print("L=\n",L)
print("U=\n",U)

A=
 [[1 8 2]
 [5 1 3]
 [2 4 7]]
P=
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
L=
 [[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.4        0.46153846 1.        ]]
U=
 [[5.         1.         3.        ]
 [0.         7.8        1.4       ]
 [0.         0.         5.15384615]]


Note the form of these.  The **P** matrix performs a rotation, **L** is lower diagonal, and **U** is upper-diagonal.

Once you have these matrices you'd like to solve an equation of the form $\mathbf{Ax}=\mathbf{b}$.  Unfortunately, to do this you have to use a different function.  Look at the ```lu_factor``` function:

In [5]:
help(linalg.lu_factor)

Help on function lu_factor in module scipy.linalg.decomp_lu:

lu_factor(a, overwrite_a=False, check_finite=True)
    Compute pivoted LU decomposition of a matrix.
    
    The decomposition is::
    
        A = P L U
    
    where P is a permutation matrix, L lower triangular with unit
    diagonal elements, and U upper triangular.
    
    Parameters
    ----------
    a : (M, M) array_like
        Matrix to decompose
    overwrite_a : bool, optional
        Whether to overwrite data in A (may increase performance)
    check_finite : bool, optional
        Whether to check that the input matrix contains only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if the inputs do contain infinities or NaNs.
    
    Returns
    -------
    lu : (N, N) ndarray
        Matrix containing U in its upper triangle, and L in its lower triangle.
        The unit diagonal elements of L are not stored.
    piv : (N,) ndarray

Unlike the ```lu``` function, ```lu_factor``` only returns two things, an $NxN$ matrix and a 1D array.  Try it here on our previous **A** matrix:

In [6]:
lu,piv = linalg.lu_factor(A)
print("lu =\n",lu)
print("piv =\n", piv)

lu =
 [[5.         1.         3.        ]
 [0.2        7.8        1.4       ]
 [0.4        0.46153846 5.15384615]]
piv =
 [1 1 2]


This looks different from the previous function, but it contains the same information, only in a condensed form.  Compare this **lu** matrix to the **L** and **U** matrices above.  This one is a combination of the previous two, with the elements of **L** on and below the diagonal, and **U** above the diagonal (the ones on the **L** diagonal are implied and ignored).  The **piv** array also has the same information, just in a different form.

Why would we use this harder to read information?  Remember our goal is to solve the formula $\mathbf{Ax}=\mathbf{b}$.  To do that, we use the function ```lu_solve```:

In [7]:
help(linalg.lu_solve)

Help on function lu_solve in module scipy.linalg.decomp_lu:

lu_solve(lu_and_piv, b, trans=0, overwrite_b=False, check_finite=True)
    Solve an equation system, a x = b, given the LU factorization of a
    
    Parameters
    ----------
    (lu, piv)
        Factorization of the coefficient matrix a, as given by lu_factor
    b : array
        Right-hand side
    trans : {0, 1, 2}, optional
        Type of system to solve:
    
        =====  =========
        trans  system
        =====  =========
        0      a x   = b
        1      a^T x = b
        2      a^H x = b
        =====  =========
    overwrite_b : bool, optional
        Whether to overwrite data in b (may increase performance)
    check_finite : bool, optional
        Whether to check that the input matrices contain only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if the inputs do contain infinities or NaNs.
    
    Returns
    -------
 

This function takes three inputs, the **lu** and **piv** matrices from the ```lu_factor``` function, and the **b** array.  It returns the **x** array, which we are trying to solve for.  For example:

In [8]:
b = np.array([4,3,8])
x = linalg.lu_solve((lu,piv),b)
print("x=\n",x)

x=
 [-0.05970149  0.25373134  1.01492537]


This is the explicit way to use LU decomposition.  However, there is an even easier way to perform the same calculation, which may be appropriate in certain circumstances.  Since LU decomposition is so popular, there is also the ```solve``` function:

In [9]:
help(linalg.solve)

Help on function solve in module scipy.linalg.basic:

solve(a, b, sym_pos=False, lower=False, overwrite_a=False, overwrite_b=False, debug=None, check_finite=True, assume_a='gen', transposed=False)
    Solves the linear equation set ``a * x = b`` for the unknown ``x``
    for square ``a`` matrix.
    
    If the data matrix is known to be a particular type then supplying the
    corresponding string to ``assume_a`` key chooses the dedicated solver.
    The available options are
    
    ===================  ========
     generic matrix       'gen'
     symmetric            'sym'
     hermitian            'her'
     positive definite    'pos'
    ===================  ========
    
    If omitted, ``'gen'`` is the default structure.
    
    The datatype of the arrays define which solver is called regardless
    of the values. In other words, even when the complex array entries have
    precisely zero imaginary parts, the complex solver will be called based
    on the data type of the arr

This function takes only the **A** and **b** matrices, and will internally do all of the LU decomposition and back-solving to find **x**.  For example:

In [10]:
x = linalg.solve(A,b)
print("x=\n",x)

x=
 [-0.05970149  0.25373134  1.01492537]


Note the similarity to the above results.  This easier approach is nice, but may not always be the best way to write your program, especially if you are going to compute multiple **x** arrays for different **b** arrays.

**Activity**: Consider the set of linear equations below:

$3*w+4*x+2*y+z=25.5$

$4*w + y -z = 22.0$

$-w + x + y + z = -2.0$

$w + x + y = 8.5$

Solve this set of linear equations for the variables $w, x, y, z$.  Do this two ways:

1.  Use the explicit LU decomposition algorithm.  That is:

  a.  Create the $\mathbf{P}, \mathbf{U},$ and $\mathbf{L}$ matrices using scipy's ```lu``` function.  
  b. Print these matricies out and verify that they have the expected shape.   
  c. Use the ```lu_factor``` function to create the compressed ```lu``` and ```piv``` matricies.  
  d. Use the ```lu_solve``` function to solve for $w, x, y,$ and $z$.

2.  Use the linalg ```solve``` function to directly solve for $w, x, y,$ and $z$. Compare the results to what you found above.


In [11]:
A = np.array([[3,4,2,1],[4,0,1,-1],[-1,1,1,1],[1,1,1,0]])
b = np.array([25.5,22.0,-2.0,8.5])

In [18]:
P,L,U = linalg.lu(A)
print("A=\n",A)
print("P=\n",P)
print("L=\n",L)
print("U=\n",U)

A=
 [[ 3  4  2  1]
 [ 4  0  1 -1]
 [-1  1  1  1]
 [ 1  1  1  0]]
P=
 [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
L=
 [[ 1.          0.          0.          0.        ]
 [ 0.75        1.          0.          0.        ]
 [-0.25        0.25        1.          0.        ]
 [ 0.25        0.25        0.46666667  1.        ]]
U=
 [[ 4.          0.          1.         -1.        ]
 [ 0.          4.          1.25        1.75      ]
 [ 0.          0.          0.9375      0.3125    ]
 [ 0.          0.          0.         -0.33333333]]


In [13]:
lu,piv = linalg.lu_factor(A)
print("lu =\n",lu)
print("piv =\n", piv)

lu =
 [[ 4.          0.          1.         -1.        ]
 [ 0.75        4.          1.25        1.75      ]
 [-0.25        0.25        0.9375      0.3125    ]
 [ 0.25        0.25        0.46666667 -0.33333333]]
piv =
 [1 1 2 3]


In [14]:
x = linalg.lu_solve((lu,piv),b)
print("x=\n",x)

x=
 [ 5.   2.   1.5 -0.5]


**Activity** For small matrices, computers are fast enough that you may not care about the efficiency of the method used to solve your system.  However, the computational cost of matrix calculations can quickly become expensive as you increase the system size.

Here, you will explore the cost of LU factorization.  The code below creates a random matrix of size $NxN$ along with a random vector of size $N$.  It then uses the linalg ```solve``` routine to find a solution to the matrix equation $\mathbf{Ax}=\mathbf{b}$.  It is wrapped with the "timeit" function that will run the code multiple (here 10) times and report how long it takes to run.  Run this code with increasing sizes of $N$.  How large of a matrix is reasonable to solve with this method? Note that the code is currently set up to time both how long it takes to make the random matricies, and to solve them.  You may wish to comment out the ```solve``` routine to determine how long just the matrix creation takes.

If you have time, also use the timeit function to see how long the ```lu_factor``` and ```lu_solve``` routines each take for a relatively large matrix.  Which part is more expensive?  For what size matrix, and under what conditions, should you consider using the ```lu_factor``` and ```lu_solve``` steps instead of the ```solve``` function? 

In [15]:
%%timeit -n 10
N = 2500
A=np.random.random([N,N])
b=np.random.random(N)
np.linalg.solve(A,b)

10 loops, best of 5: 478 ms per loop


In [16]:
%%timeit -n 10
N = 2500
A=np.random.random([N,N])
b=np.random.random(N)
lu, piv = linalg.lu_factor(A)

10 loops, best of 5: 529 ms per loop


In [17]:
%%timeit -n 10
N = 2500
A=np.random.random([N,N])
b=np.random.random(N)
lu, piv = linalg.lu_factor(A)
linalg.lu_solve((lu, piv), b)

10 loops, best of 5: 506 ms per loop


Note that most of the time is spent on the lu factorization step, not on the solving step (the differences between the times of the last two steps is minimal).  So if you have a relatively large matrix that you need to solve many times, you should take the extra work to explicitly perform the LU factorization and save it. Then each of your solving steps will be relatively quick.  But if your matrix is small, or you only need to solve it once, the ```solve``` function  is fine to use. 