<a href="https://colab.research.google.com/github/WereszczynskiClasses/Phys240_Solutions/blob/main/Arrays_For_Loops_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python lists and arrays

So far, we've used variables for storing single values of objects (whether they are integers, floats, complex numbers, or strings).  But you'll find this is fairly limited, and often you'll want to store many things in one variable.  To do this, python has several major structures. The one that will be the most useful for us are arrays, and we'll focus on them, although it's worth being familiar with the list as a first step.

##Lists

### Basic list commands
A list is a general structure that can contain entries of many variable types.  To define a list we use brackets, with entries separated by commas.  For example, to define a list of integers we could type:

```
a= [1, 2, 3]
```

To access an element of the array, place the index that you want in brackets, such as:

```
a[0]
```

Note that python uses 0-based indexing, so to access the first element of a list you need to set the index to 0 (this is similar to some languages like C++, but different from matlab and mathematica in which the first element is 1).

There are a few other nice operations you should know about with lists:

*   To edit only one element of a list, you can set that element equal to a specified value. For example:

```
a[1] = 4
```

Will change only list element 1 (the second list element since it is 0-based) to have a value of 4 while keeping all other elements the same.

*   To add an item to the end of a list you can use the append function.  The easiest way to do that for our array "a" above is:

```
a.append(4)
```

This command will expand your list, add the specified value to the end of it, and save the list

*   To remove an item from the end of the list, use the pop command:

```
a.pop()
```
This will remove the last element of the list.

* You can get the length of a list using the len command:

```
len(a)
```
*  When dealing with multiple lists, the + and * operators act just like they do for strings: + will concatenate together two lists, whereas * will repeat that list.

* There are some other potentially useful operations, please look at the python documentation on lists to see more details. [lists](https://docs.python.org/3/tutorial/datastructures.html)
 


**Activity:** To play around with lists, do the following:

1.   Create a list of five items (they can be floats, strings, or whatever you want).  Print the list to make sure it's what you wanted.
2.   Change only the third element in the list and print the list again.
3.  Add a new element to the end of the list. Check the length to make sure your list has grown in size.
4.  Create a second list and concatenate it the first list.  Print the result.

### Slicing

Often you'll want to extract more than one element from your list at a time.  For example, you might want to print the first 5 elements of your list, or every third element.  To do this, you can use slicing.  For a list, you can select the first element to be output, the last, and the stride (interval) of the selected elements.  The general format for this is ```a[start:end:stride]```.  Note that if the stride selection is omitted it is assumed to be 1.  For example:

```
a[1:5:2]
``` 

Will start selecting at element 1, stop at 4 (the element specified by end is not included) and select every other element

**Activity:** Try the following commands to familiarize yourself with slicing. Explain the output you get from each line.  Can you construct a slicing operation that returns only the odd entries of a?

In [ ]:
a=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
print(a[:])
print(a[::])
print(a[5:15])
print(a[5:15:3])
print(a[5::])
print(a[:5:])
print(a[::5])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[5, 8, 11, 14]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 1, 2, 3, 4]
[0, 5, 10, 15]


##Arrays

###Basic array functions

One of the nice things about lists is that they are fairly general data structures.  However, for our purposes they are often TOO general.  When solving physical problems, you often have a set of data on which you want to perform a set of operations.  For example, you might want to take the log of every element, which you can't easily do with a list.  

Arrays can be thought of as list with more restrictions.  The biggest restriction is that (typically) the data in arrays are all of the same type.  What we'll see is that with arrays this small restriction is worth it, because there are a lot more things we can do with them.

There is a native array module in python, but the much more popular one is based on the NumPy (numeric python) module.  There are several nice things about NumPy arrays, including:

* We can create a N-dimensional arrays 
* We can do both element wise operations (operations on each element individually) or matrix computations (for example, a cross or dot product)
* Numpy arrays are more memory efficient than lists, and the calculations on numpy arrays are typically faster than standard python operations on the same number of elements

In many of the codes we write from here on out we'll load the numpy module.  The typical alias for numpy is np.  Run the following code to load numpy:

In [ ]:
import numpy as np

### One dimensional arrays

The first step to using a numpy array is to initialize it.  There are a few common ways to do this.  If you know the values you want in the array then you can enter them similar to a list as:

```
a = np.array([1, 2, 3])
```

If you don't know all the values your array should have, a popular method is to set ever value to zero using the zeros command:

```
a = np.zeros(5)
```

This creates an array of length 5 where every element is zero. You can then edit the individual elements of the array later in your program. 

Another useful way to initialize an array is to use the arange command.  This creates a range of values from an initial lower bound to an upper bound in specified increments.

**Activity:** This is a good opportunity to get used to reading the python documentation, so go to this website: [arange documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

Note that it says the arange command can be run as:

```
numpy.arange([start, ]stop, [step, ]dtype=None)
```
The format of this states that there must be at least one argument given, which is the "stop" argument.  The "start" and "step" arguments are optional as 
Then run the following examples. Explain in words what each of them is doing:

In [ ]:
a=np.arange(5)
print(a)
a=np.arange(2,5)
print(a)
a=np.arange(2,5,.25)
print(a)

[0 1 2 3 4]
[2 3 4]
[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25 4.5  4.75]


There are also many ways to set up arrays with random numbers, and ways to read values from external files.  We'll deal with those in the future.

Once you have an array you can start to do stuff with it.  Unlike what you might expect for matrices, many operations on numpy arrays are **elementwise**, that is they are performed on each element individually.  This includes simple mathematical operations, as well as using more complex ones such as the numpy log or sine functions.  For example, try the following code:


In [ ]:
a = np.arange(1,10)
print(a)
b = a /20
print(b)
c = np.log(a)
print(c)

[1 2 3 4 5 6 7 8 9]
[0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


Note that the operations of division and log are performed on each element separately. There are operations that are performed on the whole array, for example the numpy sum and prod commands will sum and take the product of the elements of an array:

In [ ]:
print(np.sum(a))
print(np.prod(a))

45
362880


Note that you must use the numpy version of functions like log when working with a numpy array.  If you tried to use the math version it wouldn't work, since the math version expects a scalar number as an input.

**Activity:** Initialize an array with values ranging from $-\pi$ to $\pi$ in increments of 0.1.  Using the np.sin() and np.cos() functions, calculate the sine and cosine of each element in this array.  Then, square each element of your array and calculate the sine and cosine of each element.  That is, calculate $\sin(x^2)$ and $\cos(x^2)$ for x ranging from $-\pi$ to $\pi$.

In [ ]:
x=np.arange(-3.14, 3.14, .1)
print(np.sin(x))
print(np.sin(x**2))

[-0.00159265 -0.10141799 -0.20022998 -0.29704135 -0.39088478 -0.48082261
 -0.56595623 -0.645435   -0.71846479 -0.78431593 -0.84233043 -0.89192865
 -0.93261501 -0.963983   -0.98571918 -0.99760638 -0.99952583 -0.99145835
 -0.97348454 -0.945784   -0.9086335  -0.86240423 -0.8075581  -0.74464312
 -0.67428791 -0.59719544 -0.51413599 -0.42593947 -0.33348709 -0.23770263
 -0.13954311 -0.03998933  0.05996401  0.15931821  0.25708055  0.35227423
  0.44394811  0.5311862   0.61311685  0.68892145  0.75784256  0.81919157
  0.87235548  0.91680311  0.95209034  0.9778646   0.99386836  0.99994172
  0.99602399  0.98215432  0.95847128  0.92521152  0.88270735  0.83138346
  0.77175266  0.70441077  0.63003063  0.54935544  0.46319126  0.37239904
  0.27788593  0.18059627  0.08150215]
[-0.42124901  0.18215528  0.70411636  0.97769227  0.94060729  0.63376794
  0.16761968 -0.32365068 -0.72262014 -0.95378356 -0.99119649 -0.85211187
 -0.58266772 -0.2415932   0.11374594  0.43675895  0.69612996  0.87623496
  0.97483789 

### Multi-dimensional arrays

One great feature of numpy arrays is that they can be multi-dimensional.  In fact, you can have arrays that have as many dimensions as you want.  For example, to create a  3x4 2D array filled with zeros you can run the following code:

In [ ]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Note the two sets of parentheses.  The zeros command only takes one argument, but that argument is what is a *tuple* (which is similar to a list in python). An example of a 3-D array is:

In [ ]:
a = np.zeros((3,4,5))
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


To access an element of a multidimensional array, the easiest method is to put all of the indices in a single set of brackets and separate them by commas, such as:

In [ ]:
print(a[2,3,4])

0.0


You can apply any of the slicing operations discussed above for lists on arrays, and for multidimensional arrays you can apply these slices in any number of dimensions.  You'll attempt this below.

Once you have an array you want to know how big it is.  There are two commands that can be used for this, shape and size.  As the names imply, shape will tell you the dimensions of an array, and size will tell you the total number of elements.  Try this code:

In [ ]:
print(np.shape(a))

(3, 4, 5)


In [ ]:
print(np.size(a))

60


You may sometimes want to repackage an array into another shape.  For this there is the reshape commands which takes two inputs, the original array and the shape of the array you want to make it:

In [ ]:
print(np.reshape(a,(4,15)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Activity:** Using the appropriate command, create a 1-D array with elements ranging from 5 to 44 (including 44). Reshape this array into a 4x10 array, and then use the appropriate slices to print out only the values 18-21 and 28-31.

In [ ]:
a = np.arange(5,45)
b = np.reshape(a,(4,10))
print(b[1:3,3:7])

[[18 19 20 21]
 [28 29 30 31]]


# For Loops

Last class we dealt with while loops.  Now that we are familiar with lists and arrays, we can look at the much more common for loop.  Briefly, a for loop will take a sequence of elements (in our cases, either a list or an array) and for each element in that sequence perform the block of code.  For example, consider this code:

In [ ]:
x = np.arange(5)
for y in x:
  print(y**2)

0
1
4
9
16


What is happening here is that we first define an array with integers 0 to 4.  Our for loop will then go through that array, and for each element in it the variable $y$ will be assigned (that is, the statement ```for y in x``` says for each element in x, assign the variable y).  It will then execute the block of code below it using our for loop variable y.

Note that we don't even need to define x.  The code below will do the same thing:

In [ ]:
for y in np.arange(5):
  print(y**2)

0
1
4
9
16


And in fact, if we don't want to, we don't have to use the variable $y$ we defined in our for loop (it can simply be a counter):

In [ ]:
for y in np.arange(5):
  print("May the force be with you")

May the force be with you
May the force be with you
May the force be with you
May the force be with you
May the force be with you


If you have a short block of code you can make the above more compact by typing:

In [ ]:
for y in np.arange(5): print("May the force be with you")

May the force be with you
May the force be with you
May the force be with you
May the force be with you
May the force be with you


I personally don't like this as I find the code harder to read, but it's good to be aware of. 

**Activity:** It happens often in physics calculations that we need to evaluate a sum. If we have the values of the terms in the sum stored in a list or array then we can calculate the sum using the built-in function sum described above. In more complicated situations, however, it is often more convenient to use a for loop to calculate a sum. Suppose, for instance, we want to know the value of the sum $s = \sum_{k=1}^{100} (1/k)$. Write a program that utilizes a for loop to perform this calculation

This program will define a variable s, and then in the for loop add to that value of s 1/k, where k will go from 1 to 100.

In [ ]:
%%time
s = 0.0
for k in np.arange(1,101):
  s += 1.0/k
print("the sum is:",s)

the sum is: 5.187377517639621
CPU times: user 1.26 ms, sys: 0 ns, total: 1.26 ms
Wall time: 1.63 ms


###Advanced: For-loops vs vectorization

For loops are nice because they are relatively easy to understand.  However, they can be slow because each loop through the code has to be completed before another loop through can begin.  If you are concerned about performance, you want to avoid these loops if possible and use "vectorization" in which commands are applied directly to the numpy array.  

To illustrate this, we'll use a notebook special function ```%%time``` which displays that total time it takes a cell of code to run (note that the closely related ```%%timeit``` function is similar in that it runs the block of code 1000 times to get an average time, which is more accurate.  Here are two ways to perform a sum over a large array.  First, in the for loop form:


In [ ]:
%%time
x = np.arange(1000000)
y = 0.0
for z in x:
  y += z
print("The sum is:" ,y)

The sum is: 499999500000.0
CPU times: user 471 ms, sys: 2.63 ms, total: 474 ms
Wall time: 480 ms


And here is the second, vectorized, approach:

In [ ]:
%%time
x = np.arange(1000000)
print("The sum is:" ,np.sum(x))

The sum is: 499999500000
CPU times: user 1.33 ms, sys: 3.02 ms, total: 4.35 ms
Wall time: 4.31 ms


Note how much faster this code is! (I get almost 100 times faster).  If you want, try to vectorized the code you wrote above and apply the %%time functions to the for-loop and vectorized versions.  

Note that in this class for loops are perfectly fine. But the push to vectorize slow pieces of code is important for many advanced calculations

In [ ]:
%%time
k = np.arange(1.0,101.0)**(-1)
s = np.sum(k)
print("the sum is:",s)


the sum is: 5.187377517639621
CPU times: user 316 µs, sys: 47 µs, total: 363 µs
Wall time: 261 µs


##Activity: Emission Lines of Hydrogen

The Rydberg formula calculates the wavelengths of emission lines in the spectrum of various atoms. For hydrogen, this formula is:

$\frac{1}{\lambda} = R \left(\frac{1}{m^2}-\frac{1}{n^2}\right)$ 

Where $m$ and $n$ are integers beginning at 1 that correspond to the atomic quantum levels, and the Rydberg constant is:

$R = 1.097 \cdot 10^{-2} nm^{-1}$

Write a program that computes the emission wavelengths for all transitions in which $m<n<8$

In [ ]:
%reset -f

This program will compute the Rydberg emission wavelengths for hydrogen.

In [ ]:
import numpy as np

There are no user-adjustable variables to implement

The Rydberg constant in inverse nm

In [ ]:
R = 1.097e-2

Perform two loops, one over m and one over n, and in each loop compute and print the results of:

$\left(R \left(\frac{1}{m^2}-\frac{1}{n^2}\right)\right)^{-1}$ 


In [ ]:
for m in np.arange(1.0,7.0):
  print("Series for m =",m)
  for n in np.arange(m+1.0,8.0):
    invlambda = R * (m**(-2)-n**(-2))
    print(" ",invlambda**(-1),"nm")

Series for m = 1.0
  121.5436037678517 nm
  102.55241567912488 nm
  97.23488301428137 nm
  94.95594044363415 nm
  93.76220862091418 nm
  93.05682163476148 nm
Series for m = 2.0
  656.3354603463993 nm
  486.1744150714068 nm
  434.084299170899 nm
  410.2096627164995 nm
  397.04243897498225 nm
Series for m = 3.0
  1875.2441724182836 nm
  1281.9051959890612 nm
  1093.8924339106654 nm
  1005.013673655424 nm
Series for m = 4.0
  4051.453458928391 nm
  2625.341841385597 nm
  2165.68603077263 nm
Series for m = 5.0
  7458.357503936354 nm
  4652.841081738073 nm
Series for m = 6.0
  12369.399060374448 nm
